### ISSUE TITLE
Refactor - AWSId into ProviderId

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/executor-bash#128]
## Expected Behavior

Provider-specific account configuration should be determined from a provider-independent source.

## Current Behavior

Currently the executor uses `AWSId` and `AzureId` Account-layer attributes from the engine to set provider-specific runtime environment variables.

## Possible Solution

Whilst the runtime variables will always remain unique to the provider, their origin is [being consolidated into a common name](https://github.com/hamlet-io/engine/issues/1463) of `ProviderId` as a part of a [bigger change to remove provider-specific names from the Account-layer](https://github.com/hamlet-io/engine/issues/1462). The Executor should be refactored to make use of this common value for both providers.

## Context

https://github.com/hamlet-io/engine/issues/1462
https://github.com/hamlet-io/engine/issues/1463

**Comment by roleyfoley** [comment]
Given that we use these Id's to determine some of the bash executor changes what would your possible solution be to handle this? 

We currently don't have anything aside from this value which tells you what kind of account this is?

**Comment by RossMurr4y** [comment]
> Given that we use these Id's to determine some of the bash executor changes what would your possible solution be to handle this?

@roleyfoley and I had an offline discussion about this. We need to be able to define the provider on the Account-layer in the engine. With that, the places that the account switching occurs within the executor (from one provider account to another) can be updated to determine which provider the account is intended, and then use the generic identifier `ProviderId` value to switch into. I will log a ticket in the engine for this.

**Comment by RossMurr4y** [comment]
Completed.
