### ISSUE TITLE
[BUG] Template generation Exceptions not exiting with non zero exit code

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/executor-bash#77]
## Expected Behaviour
When an exception occurs in a template generation using the freemarker wrapper the process should exist with a non zero exit code so that other processes can report this failure

## Current Behaviour
When generating a template and an exception occurs the exception is logged but it doesn't seem to be picked up by the createTemplate.sh script 

## Steps to Reproduce (for bugs)
1. Run createTemplate.sh which will generate an exception in the engine

## Context
Deployments are reported as successful when they actually weren't

**Comment by roleyfoley** [comment]
Not sure if this is an issue in the executor or the freemarker wrapper, also its not completely bad when debugging that the template generation continues so that you can see where the exception happened in each template generation

**Comment by ml019** [comment]
@roleyfoley I think we can close this one?

**Comment by roleyfoley** [comment]
we sure can
